language: node_js
node_js:
  - "6"
  - "8"
before_script:
  - npm install
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
  - npm run coveralls
cache:
  directories:
    - "node_modules"